### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by mckhoi** [Moitcl/moqui-chile#13]
Hi Jens,

In https://github.com/jenshp/moqui-chile/blob/master/data/l10n.xml
Those lines are not correct?

<moqui.basic.LocalizedMessage original="week" locale="es" localized="**día**"/>
<moqui.basic.LocalizedMessage original="day" locale="es" localized="**año**"/>

By the way, I tried to translate to German and find out your structure is much better, so I will adapt the translation to your structure. Thanks.

Another question. Do you have a system running in production in Chile using hivemind and PopCommerce? What are your experiences?

**Comment by jenshp** [comment]
Those lines are not correct, fixing them now, thank you.

I do have a system in production using PopCommerce (and another one using hivemind with little usage), but mostly mantle-udm and mantle-usl with a different order. Not much workload but in daily use. The experience is quite good, and very stable.
